[package]
name = "corrosive-cuda"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "corrosive_cuda"
path = "src/lib.rs"

[dependencies]
num-traits.workspace = true
rand.workspace = true
rand_distr.workspace = true
cudarc = { workspace = true, optional = true }
once_cell.workspace = true

[features]
default = []
cuda = ["cudarc"]

[dev-dependencies]
criterion.workspace = true